"use client";

type Origin = "demo_fixture" | "public_cache" | "user_pasted";
type RunState = "idle" | "running" | "needs_evidence" | "awaiting_approval" | "approved" | "failed";
type Job = { id: string; origin: Origin; source: string; title: string; company: string; location: string; type: string; salary?: string; posted: string; retrieved_at?: string | null; cache_state?: string; url: string; skills?: string[]; description?: string; must_have?: string[]; preferred?: string[]; detail_loaded?: boolean };
type Turn = { round: number; requirement: string; question?: string; answer?: string; status?: string; evidence_ids?: string[]; verdict?: string };
type Patch = { section: string; original: string; proposed: string; evidence_ids: string[]; covered_requirements: string[]; status: string; reason: string };
type MarketReport = { score: number; coverage: number; verified_strengths: { skill: string; evidence_ids: string[]; preferred?: boolean }[]; adjacent_strengths: { skill: string; evidence_ids: string[]; reason: string; preferred?: boolean }[]; gaps: { skill: string; severity: string }[] };
type ExportCheck = { label: string; passed: boolean; detail: string };
type ExportReadiness = { passed: boolean; checks: ExportCheck[]; extracted_characters: number; verified_bullets: number };

const cx = (...values: Array<string | false | null | undefined>) => values.filter(Boolean).join(" ");
const roleSkills = (job?: Job) => job?.must_have?.length ? job.must_have : job?.skills || [];
const hasRoleDetail = (job?: Job) => Boolean(job?.detail_loaded || job?.description || job?.must_have?.length);

export function MatchPanel({ selectedJob, market, onStart, onSampleStart, onImport, onReviewRole, isRoleLoading, runState, canRun, usingDemoProfile, selectedIsPractice }: { selectedJob?: Job; market: MarketReport | null; onStart: () => void; onSampleStart: () => void; onImport: () => void; onReviewRole: () => void; isRoleLoading: boolean; runState: RunState; canRun: boolean; usingDemoProfile: boolean; selectedIsPractice: boolean }) {
  const sampleCheck = selectedIsPractice;
  const needsCv = usingDemoProfile && !selectedIsPractice;
  if (!hasRoleDetail(selectedJob)) {
    return <div className="match-layout role-detail-gate" aria-live="polite"><div className="match-story"><p className="kicker">ROLE SUMMARY LOADED</p><h3>Open this listing before checking the fit.</h3><p>Live search keeps long third-party descriptions out of the initial list. Review this one role to load its published requirements, then map them to your evidence.</p><button className="inline-primary" onClick={onReviewRole} disabled={!canRun || isRoleLoading}>{isRoleLoading ? "Loading role details…" : "Review role details"} <span>→</span></button></div><div className="requirements-list compact-loading"><div className="requirement-header"><span>ROLE REQUIREMENTS</span><small>{isRoleLoading ? "loading published details" : "review to load"}</small></div><div className="requirement-row skeleton-row"><span /><div><b /><p /></div></div><div className="requirement-row skeleton-row"><span /><div><b /><p /></div></div></div></div>;
  }
  const requirementRows = roleSkills(selectedJob);
  const action = needsCv ? onImport : sampleCheck ? onSampleStart : onStart;
  const actionLabel = runState === "running" ? "Checking fit…" : !canRun ? "Fit check paused" : needsCv ? "Import your CV to assess fit" : sampleCheck ? "Try sample fit check" : "Check my fit";
  return <div className="match-layout"><div className="match-story"><p>{selectedJob?.description || "Published role details are available for this review."}</p><div className="story-callout"><span>✦</span><div><b>{sampleCheck ? "Safe demo fit check." : "Start from the work you&apos;ve actually done."}</b><p>{sampleCheck ? usingDemoProfile ? "This is a safe demo using sample data. Nothing is submitted." : "This is a safe demo using a sample role. Nothing is submitted." : "HireSwarm maps each role requirement to a real CV or work example, separates direct matches from related experience, and keeps honest gaps visible."}</p></div></div><button className="inline-primary" onClick={action} disabled={runState === "running" || !canRun}>{actionLabel} <span>→</span></button>{needsCv && <p className="fit-prerequisite" role="note">A real fit check needs your CV. You can still explore the sample role separately.</p>}</div><div className="requirements-list"><div className="requirement-header"><span>ROLE REQUIREMENTS</span><small>{market ? "mapped to evidence" : sampleCheck ? "sample assessment" : needsCv ? "add your CV first" : "fit check — ready to assess"}</small></div>{requirementRows.map((skill, index) => { const direct = market?.verified_strengths.some((item) => item.skill === skill); const adjacent = market?.adjacent_strengths.some((item) => item.skill === skill); return <div className="requirement-row" key={skill}><span className={cx("requirement-icon", direct && "direct", adjacent && "adjacent")}>{direct ? "✓" : adjacent ? "~" : String(index + 1).padStart(2, "0")}</span><div><b>{skill}</b><p>{direct ? "Direct evidence available" : adjacent ? "Related experience — confirm the boundary" : market ? "No direct evidence found" : "Not assessed yet"}</p></div></div>; })}</div></div>;
}

export function RehearsalPanel({ turns, currentTurn, runState, onStart, canRun }: { turns: Turn[]; currentTurn?: Turn; runState: RunState; onStart: () => void; canRun: boolean }) {
  if (!turns.length && runState !== "running") return <div className="rehearsal-empty"><div className="conversation-preview"><div className="speaker-card hr"><span>HIRING PANEL</span><p>“Tell me about the evidence behind your most relevant work.”</p></div><div className="speaker-card candidate"><span>CANDIDATE TWIN</span><p>“I&apos;ll answer only from the evidence already in your profile.”</p></div></div><div><h3>A calm rehearsal, not a performance.</h3><p>A role-specific hiring-panel simulation challenges a Candidate Twin built only from your evidence. If the evidence is missing, we name the gap instead of inventing an answer.</p><button className="inline-primary" onClick={onStart} disabled={!canRun}>{canRun ? "Begin practice session" : "Practice paused"} <span>→</span></button></div></div>;
  return <div className="rehearsal-wrap"><div className="interview-status"><div><span className={cx("record-dot", runState === "running" && "recording")} /> {runState === "running" ? "Rehearsal in progress" : "Interview notes"}</div><b>{turns.length}/4 prompts reviewed</b></div><div className="conversation-list">{turns.map((turn) => <article className="conversation-turn" key={turn.round}><div className="turn-marker">{String(turn.round).padStart(2, "0")}</div><div className="turn-content"><div className="question-bubble"><span>HIRING PANEL · {turn.requirement}</span><p>{turn.question || "Preparing the next role-specific question…"}</p></div>{turn.answer && <div className="answer-bubble"><span>CANDIDATE TWIN · <b className={cx("status-word", turn.status?.toLowerCase())}>{turn.status}</b></span><p>{turn.answer}</p>{turn.evidence_ids?.length ? <div className="source-pills">{turn.evidence_ids.map((id) => <i key={id}>{id}</i>)}</div> : null}</div>}{turn.verdict && <div className={cx("verdict", turn.status?.toLowerCase())}>{turn.verdict}</div>}</div></article>)}</div>{runState === "running" && <div className="now-thinking"><span /><p>{currentTurn?.question ? "Checking the answer against your evidence…" : "Preparing the next interview prompt…"}</p></div>}</div>;
}

export function TailorPanel({ patches, coverLetter, coverLetterEvidenceIds, showCoverLetter, onToggleCoverLetter, onStart, canRun, runState }: { patches: Patch[]; coverLetter: string; coverLetterEvidenceIds: string[]; showCoverLetter: boolean; onToggleCoverLetter: () => void; onStart: () => void; canRun: boolean; runState: RunState }) {
  if (!patches.length) return <div className="tailor-empty"><div className="paper-stack"><span /><span /><article><small>YOUR RESUME</small><b>Relevant work, clearly stated.</b><p>The strongest application is specific about what you did — and careful about what you did not do.</p></article></div><div><h3>Your resume will stay yours.</h3><p>Once the rehearsal is complete, HireSwarm suggests small, source-linked changes. You see every original sentence before deciding what to keep.</p><button className="inline-primary" onClick={onStart} disabled={!canRun || runState === "running"}>{runState === "running" ? "Evidence check in progress" : canRun ? "Run the evidence check" : "Evidence check paused"} <span>→</span></button></div></div>;
  if (showCoverLetter) return <div className="letter-view"><div className="letter-toolbar"><div><span>APPLICATION NOTE</span><b>Draft cover letter</b></div><button className="text-action" onClick={onToggleCoverLetter}>Back to revisions</button></div>{coverLetterEvidenceIds.length > 0 && <div className="letter-evidence"><span>Bound to evidence</span>{coverLetterEvidenceIds.map((id) => <i key={id}>{id}</i>)}</div>}<pre>{coverLetter}</pre></div>;
  return <div className="revision-wrap"><div className="revision-toolbar"><div><span>{patches.length} suggested changes</span><p>Each revision carries its evidence trail.</p></div><button className="outline-action small" onClick={onToggleCoverLetter} disabled={!coverLetter}>Read cover letter</button></div><div className="revision-list">{patches.map((patch, index) => <article className="revision" key={`${patch.original}-${index}`}><div className="revision-number">{String(index + 1).padStart(2, "0")}</div><div className="revision-body"><div className="revision-section">{patch.section}</div>{patch.proposed.trim() === patch.original.trim() ? <><p className="before source-only">SOURCE SENTENCE</p><p className="after">Keep this exact wording; prioritize it in this section for the target role.</p></> : <><p className="before"><s>{patch.original}</s></p><p className="after">{patch.proposed}</p></>}<div className="revision-meta"><span>Backed by {patch.evidence_ids.map((id) => <i key={id}>{id}</i>)}</span><em>{patch.reason}</em></div></div></article>)}</div></div>;
}

export function ReviewPanel({ runState, patches, gaps, readiness, selectedJob, onApprove, onExport, onOpenOfficial, serviceOnline, isApproving, isExporting }: { runState: RunState; patches: Patch[]; gaps: { skill: string; severity: string }[]; readiness: ExportReadiness | null; selectedJob?: Job; onApprove: () => void; onExport: (format: "docx" | "pdf") => void; onOpenOfficial: (url?: string) => void; serviceOnline: boolean; isApproving: boolean; isExporting: "docx" | "pdf" | null }) {
  const ready = runState === "awaiting_approval" || runState === "approved";
  const isRunning = runState === "running";
  const extractionPassed = readiness?.checks.find((item) => item.label === "PDF text round-trip")?.passed ?? false;
  return <div className="review-layout">
    <div className="review-lead"><div className={cx("review-seal", runState === "approved" && "approved")}>{runState === "approved" ? "✓" : "01"}</div><div><h3>{runState === "approved" ? "You're ready to apply on your terms." : ready ? "A final read is all that's left." : isRunning ? "The packet is still being prepared." : "The application packet will appear here."}</h3><p>{runState === "approved" ? "Your verified revisions and cover letter are ready to take with you. HireSwarm will never submit an application for you." : ready ? "Check the rewritten sentences, acknowledge the gaps that remain, then approve the packet when it sounds like you." : isRunning ? "Approval and downloads stay locked until the evidence rehearsal reaches your review step." : "Complete the rehearsal and tailoring steps to create a document you can review."}</p></div></div>
    {isRunning && <p className="review-running-note" role="status">The rehearsal is active. Approval and exports will unlock only after it has finished and presented its evidence-bound review.</p>}
    <div className="review-checks"><ReviewCheck complete={patches.length > 0} label={`${patches.length || "No"} evidence-linked resume revisions`} /><ReviewCheck complete label={gaps.length ? `${gaps.length} growth area${gaps.length > 1 ? "s" : ""} kept visible` : "No unmet role requirements detected"} /><ReviewCheck complete={Boolean(readiness?.passed && extractionPassed)} label={readiness?.passed ? "One-column export passed a real PDF text check" : "Export readiness will be checked before approval"} /><ReviewCheck complete={runState === "approved"} label={runState === "approved" ? "Your approval has been recorded" : "Your approval is still required"} /></div>
    {readiness && <div className="readiness-note"><span>{readiness.passed ? "✓" : "!"}</span><p><b>Document QA</b> · {readiness.verified_bullets} verified bullet{readiness.verified_bullets === 1 ? "" : "s"}; {readiness.extracted_characters} characters read back from the generated PDF.</p></div>}
    <div className="review-actions">
      {runState === "awaiting_approval" && <button className="approve-action" onClick={onApprove} disabled={!serviceOnline || isApproving}>{!serviceOnline ? "Approval paused" : isApproving ? "Saving your approval…" : "I've reviewed this packet"} <span>→</span></button>}
      {runState === "approved" && <><button className="approve-action export" onClick={() => onExport("docx")} disabled={!serviceOnline || Boolean(isExporting)}>{isExporting === "docx" ? "Preparing .docx…" : "Download .docx"} <span>↓</span></button><button className="outline-action" onClick={() => onExport("pdf")} disabled={!serviceOnline || Boolean(isExporting)}>{isExporting === "pdf" ? "Preparing PDF…" : "Printable PDF"} <span>↓</span></button>{selectedJob?.url && selectedJob.origin !== "demo_fixture" && <button className="outline-action" onClick={() => onOpenOfficial(selectedJob.url)} disabled={Boolean(isExporting)}>Open official listing ↗</button>}</>}
      {!ready && !isRunning && <span className="locked-action">Complete a rehearsal to unlock review</span>}
    </div>
  </div>;
}

function ReviewCheck({ complete, label }: { complete: boolean; label: string }) { return <div className={cx("review-check", complete && "complete")}><span>{complete ? "✓" : "○"}</span><p>{label}</p></div>; }
